version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: turf_novo
      POSTGRES_USER: turf_novo_user
      POSTGRES_PASSWORD: T!_!RF-N0vO
    ports:
      - "5433:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
